/*
 * Created on 16 févr. 2014 ( Time 14:24:48 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package edu.prog3.tp.association.persistence.services.fake;

import java.util.List;
import java.util.Map;

import edu.prog3.tp.association.bean.Adherent ;
import edu.prog3.tp.association.persistence.commons.fake.GenericFakeService;
import edu.prog3.tp.association.persistence.services.AdherentPersistence;

/**
 * Fake persistence service implementation ( entity "Adherent" )
 *
 * @author Telosys Tools Generator
 */
public class AdherentPersistenceFAKE extends GenericFakeService<Adherent> implements AdherentPersistence {

	public AdherentPersistenceFAKE () {
		super(Adherent.class);
	}
	
	protected Adherent buildEntity(int index) {
		Adherent entity = new Adherent();
		// Init fields with mock values
		entity.setId( nextString() ) ;
		entity.setMdp( nextString() ) ;
		entity.setNom( nextString() ) ;
		entity.setPrenom( nextString() ) ;
		entity.setAdresse( nextString() ) ;
		entity.setCp( nextString() ) ;
		entity.setVille( nextString() ) ;
		entity.setPays( nextString() ) ;
		return entity ;
	}
	
	
	public boolean delete(Adherent entity) {
		log("delete ( Adherent : " + entity + ")" ) ;
		return true;
	}

	public boolean delete( String id ) {
		log("delete ( PK )") ;
		return true;
	}

	public Adherent insert(Adherent entity) {
		log("insert ( Adherent : " + entity + ")" ) ;
		return entity;
	}

	public Adherent load( String id ) {
		log("load ( PK )") ;
		return buildEntity(1) ; 
	}

	public List<Adherent> loadAll() {
		log("loadAll()") ;
		return buildList(40) ;
	}

	public List<Adherent> loadByNamedQuery(String queryName) {
		log("loadByNamedQuery ( '" + queryName + "' )") ;
		return buildList(20) ;
	}

	public List<Adherent> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) {
		log("loadByNamedQuery ( '" + queryName + "', parameters )") ;
		return buildList(10) ;
	}

	public Adherent save(Adherent entity) {
		log("insert ( Adherent : " + entity + ")" ) ;
		return entity;
	}

	public List<Adherent> search(Map<String, Object> criteria) {
		log("search (criteria)" ) ;
		return buildList(15) ;
	}

	
	public long countAll() {
		return 0 ;
	}

}
