/*
 * Created on 16 févr. 2014 ( Time 14:24:48 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package edu.prog3.tp.association.persistence.services.fake;

import java.util.List;
import java.util.Map;

import edu.prog3.tp.association.bean.Article ;
import edu.prog3.tp.association.persistence.commons.fake.GenericFakeService;
import edu.prog3.tp.association.persistence.services.ArticlePersistence;

/**
 * Fake persistence service implementation ( entity "Article" )
 *
 * @author Telosys Tools Generator
 */
public class ArticlePersistenceFAKE extends GenericFakeService<Article> implements ArticlePersistence {

	public ArticlePersistenceFAKE () {
		super(Article.class);
	}
	
	protected Article buildEntity(int index) {
		Article entity = new Article();
		// Init fields with mock values
		entity.setCode( nextInteger() ) ;
		entity.setNom( nextString() ) ;
		entity.setPrix( nextDouble() ) ;
		entity.setStock( nextInteger() ) ;
		return entity ;
	}
	
	
	public boolean delete(Article entity) {
		log("delete ( Article : " + entity + ")" ) ;
		return true;
	}

	public boolean delete( Integer code ) {
		log("delete ( PK )") ;
		return true;
	}

	public Article insert(Article entity) {
		log("insert ( Article : " + entity + ")" ) ;
		return entity;
	}

	public Article load( Integer code ) {
		log("load ( PK )") ;
		return buildEntity(1) ; 
	}

	public List<Article> loadAll() {
		log("loadAll()") ;
		return buildList(40) ;
	}

	public List<Article> loadByNamedQuery(String queryName) {
		log("loadByNamedQuery ( '" + queryName + "' )") ;
		return buildList(20) ;
	}

	public List<Article> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) {
		log("loadByNamedQuery ( '" + queryName + "', parameters )") ;
		return buildList(10) ;
	}

	public Article save(Article entity) {
		log("insert ( Article : " + entity + ")" ) ;
		return entity;
	}

	public List<Article> search(Map<String, Object> criteria) {
		log("search (criteria)" ) ;
		return buildList(15) ;
	}

	public long countAll() {
		return 0 ;
	}

	public List<Article> getArticleInStock(int value) {
		// TODO Auto-generated method stub
		return null;
	}

}
