/*
 * Created on 16 févr. 2014 ( Time 14:24:48 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package edu.prog3.tp.association.persistence.services.fake;

import java.util.List;
import java.util.Map;

import edu.prog3.tp.association.bean.Adherent;
import edu.prog3.tp.association.bean.Commande ;
import edu.prog3.tp.association.persistence.commons.fake.GenericFakeService;
import edu.prog3.tp.association.persistence.services.CommandePersistence;

/**
 * Fake persistence service implementation ( entity "Commande" )
 *
 * @author Telosys Tools Generator
 */
public class CommandePersistenceFAKE extends GenericFakeService<Commande> implements CommandePersistence {

	public CommandePersistenceFAKE () {
		super(Commande.class);
	}
	
	protected Commande buildEntity(int index) {
		Commande entity = new Commande();
		// Init fields with mock values
		entity.setId( nextInteger() ) ;
		entity.setDateCmd( nextDate() ) ;
		return entity ;
	}
	
	
	public boolean delete(Commande entity) {
		log("delete ( Commande : " + entity + ")" ) ;
		return true;
	}

	public boolean delete( Integer id ) {
		log("delete ( PK )") ;
		return true;
	}

	public Commande insert(Commande entity) {
		log("insert ( Commande : " + entity + ")" ) ;
		return entity;
	}

	public Commande load( Integer id ) {
		log("load ( PK )") ;
		return buildEntity(1) ; 
	}

	public List<Commande> loadAll() {
		log("loadAll()") ;
		return buildList(40) ;
	}

	public List<Commande> loadByNamedQuery(String queryName) {
		log("loadByNamedQuery ( '" + queryName + "' )") ;
		return buildList(20) ;
	}

	public List<Commande> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) {
		log("loadByNamedQuery ( '" + queryName + "', parameters )") ;
		return buildList(10) ;
	}

	public Commande save(Commande entity) {
		log("insert ( Commande : " + entity + ")" ) ;
		return entity;
	}

	public List<Commande> search(Map<String, Object> criteria) {
		log("search (criteria)" ) ;
		return buildList(15) ;
	}


	public long countAll() {
		return 0 ;
	}

	public long countByAdherent(Adherent adh) {
		// TODO Auto-generated method stub
		return 0;
	}

}
