/*
 * Created on 16 févr. 2014 ( Time 14:24:48 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package edu.prog3.tp.association.persistence.services.fake;

import java.util.List;
import java.util.Map;

import edu.prog3.tp.association.bean.Article;
import edu.prog3.tp.association.bean.Commande;
import edu.prog3.tp.association.bean.CommandeArticle ;
import edu.prog3.tp.association.persistence.commons.fake.GenericFakeService;
import edu.prog3.tp.association.persistence.services.CommandeArticlePersistence;

/**
 * Fake persistence service implementation ( entity "CommandeArticle" )
 *
 * @author Telosys Tools Generator
 */
public class CommandeArticlePersistenceFAKE extends GenericFakeService<CommandeArticle> implements CommandeArticlePersistence {

	public CommandeArticlePersistenceFAKE () {
		super(CommandeArticle.class);
	}
	
	protected CommandeArticle buildEntity(int index) {
		CommandeArticle entity = new CommandeArticle();
		// Init fields with mock values
		entity.setQuantite( nextInteger() ) ;
		return entity ;
	}
	
	
	public boolean delete(CommandeArticle entity) {
		log("delete ( CommandeArticle : " + entity + ")" ) ;
		return true;
	}

	public boolean delete( Integer commandeId, Integer articleCode ) {
		log("delete ( PK )") ;
		return true;
	}

	public CommandeArticle insert(CommandeArticle entity) {
		log("insert ( CommandeArticle : " + entity + ")" ) ;
		return entity;
	}

	public CommandeArticle load( Integer commandeId, Integer articleCode ) {
		log("load ( PK )") ;
		return buildEntity(1) ; 
	}

	public List<CommandeArticle> loadAll() {
		log("loadAll()") ;
		return buildList(40) ;
	}

	public List<CommandeArticle> loadByNamedQuery(String queryName) {
		log("loadByNamedQuery ( '" + queryName + "' )") ;
		return buildList(20) ;
	}

	public List<CommandeArticle> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) {
		log("loadByNamedQuery ( '" + queryName + "', parameters )") ;
		return buildList(10) ;
	}

	public CommandeArticle save(CommandeArticle entity) {
		log("insert ( CommandeArticle : " + entity + ")" ) ;
		return entity;
	}

	public List<CommandeArticle> search(Map<String, Object> criteria) {
		log("search (criteria)" ) ;
		return buildList(15) ;
	}

	public long countAll() {
		return 0 ;
	}

	public List<CommandeArticle> getAllArticleByCommande(Commande order) {
		// TODO Auto-generated method stub
		return null;
	}

}
