
/*
 * Created on 16 févr. 2014 ( Time 14:24:48 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package edu.prog3.tp.association.mock;

import java.util.LinkedList;
import java.util.List;

import edu.prog3.tp.association.bean.Article ;
import edu.prog3.tp.association.mock.tool.MockValues;

public class ArticleMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public Article createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextInteger() );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public Article createInstance( Integer code ) {
		Article entity = new Article();
		// Init Primary Key fields
		entity.setCode( code) ;
		// Init Data fields
		entity.setNom( mockValues.nextString(25) ) ; // java.lang.String 
		entity.setPrix( mockValues.nextDouble() ) ; // java.lang.Double 
		entity.setStock( mockValues.nextInteger() ) ; // java.lang.Integer 
		// Init Link fields (if any)
		// setListOfCommandeArticle( TODO ) ; // List<CommandeArticle> 
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<Article> createList(int count) {
		List<Article> list = new LinkedList<Article>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
