/*
 * Created on 16 févr. 2014 ( Time 14:24:48 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package edu.prog3.tp.association.test.persistence;


import java.util.ArrayList;

import edu.prog3.tp.association.bean.Article ;
import edu.prog3.tp.association.mock.ArticleMock;
import edu.prog3.tp.association.persistence.PersistenceServiceProvider;
import edu.prog3.tp.association.persistence.services.ArticlePersistence;

import org.junit.Assert;
import org.junit.Test;

/**
 * JUnit test case for Article persistence service
 * 
 * @author Telosys Tools Generator
 *
 */
public class ArticlePersistenceTest 
{
	@Test
	public void test1() {
		
		System.out.println("Test count ..." );
		
		ArticlePersistence service = PersistenceServiceProvider.getService(ArticlePersistence.class);
		System.out.println("CountAll = " + service.countAll() );
	}
	
	@Test
	public void test2() {
		System.out.println("Test get article in stock ..." );
		
		ArticlePersistence service = PersistenceServiceProvider.getService(ArticlePersistence.class);
		ArrayList<Article> a = (ArrayList<Article>) service.getArticleInStock(0);
		for (Article article : a) {
			Assert.assertTrue(article.getStock()>0);
		}
	}

}
