/*
 * Created on 16 févr. 2014 ( Time 14:24:48 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package edu.prog3.tp.association.test.persistence;


import edu.prog3.tp.association.bean.CommandeArticle ;
import edu.prog3.tp.association.mock.CommandeArticleMock;
import edu.prog3.tp.association.persistence.PersistenceServiceProvider;
import edu.prog3.tp.association.persistence.services.CommandeArticlePersistence;

import org.junit.Assert;
import org.junit.Test;

/**
 * JUnit test case for CommandeArticle persistence service
 * 
 * @author Telosys Tools Generator
 *
 */
public class CommandeArticlePersistenceTest 
{
	@Test
	public void test1() {
		
		System.out.println("Test count ..." );
		
		CommandeArticlePersistence service = PersistenceServiceProvider.getService(CommandeArticlePersistence.class);
		System.out.println("CountAll = " + service.countAll() );
	}
	
	@Test
	public void test2() {
		
		System.out.println("Test CommandeArticle persistence : delete + load ..." );
		
		CommandeArticlePersistence service = PersistenceServiceProvider.getService(CommandeArticlePersistence.class);
		
		CommandeArticleMock mock = new CommandeArticleMock();
		
		// TODO : set primary key values here 
		process( service, mock, 0 , 0  );
		// process( service, mock, ... );
	}

	private void process(CommandeArticlePersistence service, CommandeArticleMock mock, Integer commandeId, Integer articleCode ) {
		System.out.println("----- "  );
		System.out.println(" . load : " );
		CommandeArticle entity = service.load( commandeId, articleCode );
		if ( entity != null ) {
			// Found 
			System.out.println("   FOUND : " + entity );
			
			// Save (update) with the same values to avoid database integrity errors  
			System.out.println(" . save : " + entity );
			service.save(entity);
			System.out.println("   saved : " + entity );
		}
		else {
			// Not found 
			System.out.println("   NOT FOUND" );
			// Create a new instance 
			entity = mock.createInstance( commandeId, articleCode ) ;
			Assert.assertNotNull(entity);

			// This entity references the following entities : 
			// . Commande
			// . Article
			/* Insert only if references are OK
			// Try to insert the new instance
			System.out.println(" . insert : " + entity );
			service.insert(entity);
			System.out.println("   inserted : " + entity );
			*/

			System.out.println(" . delete : " );
			boolean deleted = service.delete( commandeId, articleCode );
			System.out.println("   deleted = " + deleted);
		}		
	}
}
