/*
 * Created on 16 févr. 2014 ( Time 14:24:48 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package edu.prog3.tp.association.bean;
import java.io.Serializable;

import javax.persistence.*;

/**
 * Composite primary key for entity "CommandeArticle" ( stored in table "COMMANDE_ARTICLE" )
 *
 * @author Telosys Tools Generator
 *
 */
 @Embeddable
public class CommandeArticleKey implements Serializable
{
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY KEY ATTRIBUTES 
    //----------------------------------------------------------------------
    @Column(name="COMMANDE_ID", nullable=false)
    private Integer    commandeId   ;
    
    @Column(name="ARTICLE_CODE", nullable=false)
    private Integer    articleCode  ;
    

    //----------------------------------------------------------------------
    // CONSTRUCTORS
    //----------------------------------------------------------------------
    public CommandeArticleKey()
    {
        super();
    }

    public CommandeArticleKey( Integer commandeId, Integer articleCode )
    {
        super();
        this.commandeId = commandeId ;
        this.articleCode = articleCode ;
    }
    
    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR KEY FIELDS
    //----------------------------------------------------------------------
    public void setCommandeId( Integer value )
    {
        this.commandeId = value;
    }
    public Integer getCommandeId()
    {
        return this.commandeId;
    }

    public void setArticleCode( Integer value )
    {
        this.articleCode = value;
    }
    public Integer getArticleCode()
    {
        return this.articleCode;
    }


    //----------------------------------------------------------------------
    // equals METHOD
    //----------------------------------------------------------------------
	public boolean equals(Object obj) { 
		if ( this == obj ) return true ; 
		if ( obj == null ) return false ;
		if ( this.getClass() != obj.getClass() ) return false ; 
		CommandeArticleKey other = (CommandeArticleKey) obj; 
		//--- Attribute commandeId
		if ( commandeId == null ) { 
			if ( other.commandeId != null ) 
				return false ; 
		} else if ( ! commandeId.equals(other.commandeId) ) 
			return false ; 
		//--- Attribute articleCode
		if ( articleCode == null ) { 
			if ( other.articleCode != null ) 
				return false ; 
		} else if ( ! articleCode.equals(other.articleCode) ) 
			return false ; 
		return true; 
	} 


    //----------------------------------------------------------------------
    // hashCode METHOD
    //----------------------------------------------------------------------
	public int hashCode() { 
		final int prime = 31; 
		int result = 1; 
		
		//--- Attribute commandeId
		result = prime * result + ((commandeId == null) ? 0 : commandeId.hashCode() ) ; 
		//--- Attribute articleCode
		result = prime * result + ((articleCode == null) ? 0 : articleCode.hashCode() ) ; 
		
		return result; 
	} 


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString()
    {
		StringBuffer sb = new StringBuffer(); 
		sb.append(commandeId); 
		sb.append("|"); 
		sb.append(articleCode); 
        return sb.toString();
    }
}
