/*
 * Created on 16 févr. 2014 ( Time 14:24:48 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package edu.prog3.tp.association.bean;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;
import java.util.List;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "COMMANDE"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="COMMANDE", schema="ASSO" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="Commande.countAll", query="SELECT COUNT(x) FROM Commande x" ),
  @NamedQuery ( name="Commande.countByAdherent", query="SELECT COUNT(x) FROM Commande x WHERE x.adherent.id = :id" )

} )
public class Commande implements Serializable
{
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="ID", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Temporal(TemporalType.DATE)
    @Column(name="DATE_CMD", nullable=false)
    private Date       dateCmd      ;

	// "idAdherent" (column "ID_ADHERENT") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="ID_ADHERENT", referencedColumnName="ID")
    private Adherent   adherent    ;

    @OneToMany(mappedBy="commande", targetEntity=CommandeArticle.class)
    private List<CommandeArticle> listOfCommandeArticle;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Commande()
    {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id )
    {
        this.id = id ;
    }
    public Integer getId()
    {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : DATE_CMD ( DATE ) 
    public void setDateCmd( Date dateCmd )
    {
        this.dateCmd = dateCmd;
    }
    public Date getDateCmd()
    {
        return this.dateCmd;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setAdherent( Adherent adherent )
    {
        this.adherent = adherent;
    }
    public Adherent getAdherent()
    {
        return this.adherent;
    }

    public void setListOfCommandeArticle( List<CommandeArticle> listOfCommandeArticle )
    {
        this.listOfCommandeArticle = listOfCommandeArticle;
    }
    public List<CommandeArticle> getListOfCommandeArticle()
    {
        return this.listOfCommandeArticle;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(dateCmd);
        return sb.toString(); 
    } 

}
