/*
 * Created on 16 févr. 2014 ( Time 14:24:48 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */

package edu.prog3.tp.association.persistence.services.jpa;


import javax.persistence.EntityManager;
import javax.persistence.PersistenceException;
import javax.persistence.Query;

import edu.prog3.tp.association.bean.Adherent ;
import edu.prog3.tp.association.persistence.commons.jpa.GenericJpaService;
import edu.prog3.tp.association.persistence.commons.jpa.JpaOperation;
import edu.prog3.tp.association.persistence.services.AdherentPersistence;

/**
 * JPA implementation for basic persistence operations ( entity "Adherent" )
 * 
 * @author Telosys Tools Generator
 *
 */
public class AdherentPersistenceJPA extends GenericJpaService<Adherent, String> implements AdherentPersistence {

	/**
	 * Constructor
	 */
	public AdherentPersistenceJPA() {
		super(Adherent.class);
	}

	@Override
	public Adherent load( String id ) {
		return super.load( id );
	}

	@Override
	public boolean delete( String id ) {
		return super.delete( id );
	}

	public boolean delete(Adherent entity) {
		if ( entity != null ) {
			return super.delete( entity.getId() );
		}
		return false ;
	}

	public long countAll() {
		// JPA operation definition 
		JpaOperation operation = new JpaOperation() {
			public Object exectue(EntityManager em) throws PersistenceException {
				Query query = em.createNamedQuery("Adherent.countAll");
				return query.getSingleResult() ;
			}
		} ;
		// JPA operation execution 
		return (Long) execute(operation);
	}

}
